/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
// Note: This file is required to make NativeWind work with TypeScript preventing constant errors about missing types.
// See: https://www.nativewind.dev/quick-starts/typescript